<a href="https://colab.research.google.com/github/amitranjan02/Berkeley-433.1/blob/master/Copy_of_Example_0_Tables_and_Numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Commonly seen tables
list_of_1d_examples = [[1, 1], [0, 0], [1, 0]] # e.g. examples of vectorized features.
list_of_2d_examples = [[[0, 2], [1, 0]], [[1, 1], [1, 1]]] # e.g. examples of grey-scale images
# ... this applies to higher dimensions.

In [0]:
# Convert to numpy arrays
import numpy as np
array_of_1d_examples = np.array(list_of_1d_examples)
array_of_2d_examples = np.array(list_of_2d_examples)
print(array_of_2d_examples)

[[[0 2]
  [1 0]]

 [[1 1]
  [1 1]]]


In [0]:
### Some useful numpy array operations...
# different slicings
print ('original:\n', array_of_2d_examples[:])
print ('first example:\n', array_of_2d_examples[0])
print ('a row(*) of the first example:\n', array_of_2d_examples[0, 0, :])
print ('a row(*) of the first example:\n', array_of_2d_examples[0, -1, :])
print ('a column(*) of the first example:\n', array_of_2d_examples[0, :, 0])

original:
 [[[0 2]
  [1 0]]

 [[1 1]
  [1 1]]]
first example:
 [[0 2]
 [1 0]]
a row(*) of the first example:
 [0 2]
a row(*) of the first example:
 [1 0]
a column(*) of the first example:
 [0 1]


In [0]:
# Concatenations
# np.hstack
print(np.concatenate([array_of_1d_examples, [[0, 1]]], axis=0))
# np.vstack
print(np.concatenate([array_of_1d_examples, [[1], [0], [1]]], axis=1))

[[1 1]
 [0 0]
 [1 0]
 [0 1]]
[[1 1 1]
 [0 0 0]
 [1 0 1]]


In [0]:
# Python 0-d ~ 4-d arrays
table_0d = 0
table_1d = [0]
table_2d = [[0]]
table_3d = [[[0]]]
table_4d = [[[[0]]]]


In [0]:
# Reshape high-dimension arrays to low-dimension arrays
print(array_of_2d_examples.reshape(2, 4))

[[0 2 1 0]
 [1 1 1 1]]


In [0]:
# array-vs-array and array-vs-number operations.
print(array_of_1d_examples + 100)
print(array_of_1d_examples)
print(array_of_1d_examples / [[2], [1e-9], [1]])
print(array_of_1d_examples + array_of_1d_examples)

[[101 101]
 [100 100]
 [101 100]]
[[1 1]
 [0 0]
 [1 0]]
[[0.5 0.5]
 [0.  0. ]
 [1.  0. ]]
[[2 2]
 [0 0]
 [2 0]]


In [0]:
# conditional updates
print(array_of_1d_examples == 1)
local_array = array_of_1d_examples.copy()
local_array[array_of_1d_examples == 1] = 1
print(local_array)

[[ True  True]
 [False False]
 [ True False]]
[[1 1]
 [0 0]
 [1 0]]


In [0]:
# Some basic math functions just FYI.
# print(array_of_1d_examples.mean(axis=1))
# [[1 1], [0, 0]]
# axis = 0: a = [1, 1], b = [0, 0]
#           mean(a + b)
# axis = 1: {(1), (1)}, {(0), (0)}
# a0 = 1, b0 = 1, mean(a + b)
# a1 = 0, b1 = 0, mean(a + b)

print(array_of_2d_examples)
# print(array_of_2d_examples.mean(axis=0))
# a = [[0 2], [1 0]] 
# b = [[1 1], [1 1]]
# mean([a, b]) = a + b / 2
# print(array_of_2d_examples.mean(axis=1))
# [mean([0 2], [1 0]),
#  mean([1 1], [1 1])]
print(array_of_2d_examples.mean(axis=2))
#[[[0 2]
# [1 0]]
#
# [[1 1]
#  [1 1]]]
# axis = 0
# mean([[[0 2]
#        [1 0]]
#      [[1 1]
#       [1 1]]])
#
#[mean([[0 2]
#      [1 0]],
# mean[[1 1]
#      [1 1]] )] 
#

#[[mean([0 2])
#  mean([1 0])]
#
# [mean([1 1])
#  [1 1]]]

[[[0 2]
  [1 0]]

 [[1 1]
  [1 1]]]
[[1.  0.5]
 [1.  1. ]]


In [0]:
new_array_of_2d_examples = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                            [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]
new_array_of_2d_examples = np.array(new_array_of_2d_examples)
#print(new_array_of_2d_examples.mean(axis=0)) # 2 element of 3 x 4
# avg([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
#     [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]])
#print(new_array_of_2d_examples.mean(axis=1)) 
# [avg([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]), # 3 elements of 4
#  avg([[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]])]
print(new_array_of_2d_examples.mean(axis=2))
# [([avg([1, 2, 3, 4]), [5, 6, 7, 8], [9, 10, 11, 12]]), # 3 elements of 4
#  ([[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]])]


[[ 2.5  6.5 10.5]
 [14.5 18.5 22.5]]


In [0]:
# Pandas DataFrame: data + metadata
import pandas as pd
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data',
                 header=None,
                 names=['type1', 'type2', 'num1', 'num2', 'size', '?', '??'])
print('df:\n', df[:10])
print(type(df.keys))
print(type(df.values))
print(df.values)

df:
    type1  type2 num1 num2   size     ?     ??
0  vhigh  vhigh    2    2  small   low  unacc
1  vhigh  vhigh    2    2  small   med  unacc
2  vhigh  vhigh    2    2  small  high  unacc
3  vhigh  vhigh    2    2    med   low  unacc
4  vhigh  vhigh    2    2    med   med  unacc
5  vhigh  vhigh    2    2    med  high  unacc
6  vhigh  vhigh    2    2    big   low  unacc
7  vhigh  vhigh    2    2    big   med  unacc
8  vhigh  vhigh    2    2    big  high  unacc
9  vhigh  vhigh    2    4  small   low  unacc
<class 'method'>
<class 'numpy.ndarray'>
[['vhigh' 'vhigh' '2' ... 'small' 'low' 'unacc']
 ['vhigh' 'vhigh' '2' ... 'small' 'med' 'unacc']
 ['vhigh' 'vhigh' '2' ... 'small' 'high' 'unacc']
 ...
 ['low' 'low' '5more' ... 'big' 'low' 'unacc']
 ['low' 'low' '5more' ... 'big' 'med' 'good']
 ['low' 'low' '5more' ... 'big' 'high' 'vgood']]


In [0]:
# Convert data to numerical form for them to make sense
mapping = {'small': 1, 'med': 2, 'big': 3}
df = df.replace({'size': mapping})

print(df[:10])

   type1  type2 num1 num2  size     ?     ??
0  vhigh  vhigh    2    2     1   low  unacc
1  vhigh  vhigh    2    2     1   med  unacc
2  vhigh  vhigh    2    2     1  high  unacc
3  vhigh  vhigh    2    2     2   low  unacc
4  vhigh  vhigh    2    2     2   med  unacc
5  vhigh  vhigh    2    2     2  high  unacc
6  vhigh  vhigh    2    2     3   low  unacc
7  vhigh  vhigh    2    2     3   med  unacc
8  vhigh  vhigh    2    2     3  high  unacc
9  vhigh  vhigh    2    4     1   low  unacc
